import "./globals.css";
import { Open_Sans } from "next/font/google";
import classNames from "classnames/bind";
import styles from "./layout.module.scss";
import NavBar from "./components/nav-bar/index";
const openSans = Open_Sans({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};
const ss = classNames.bind(styles);
export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={ss("wrapper")}>
        <NavBar />

        <div className={ss("content")}>{children}</div>
      </body>
    </html>
  );
}
